from pathlib import Path

from pmc15_pipeline.data import (
    decompress_pubmed_files,
    download_pubmed_file_list,
    download_pubmed_files_from_list,
    export_keyword_captions_to_csv,
)

# Step 1: Download PubMed file list (optional if already downloaded)
# download_pubmed_file_list()

# Step 2: Download a subset of files (optional if already downloaded)
# download_pubmed_files_from_list(
#     file_list_path=Path("D:/dew_med/med_txt02/pm_ids/pmc_result_med00_sorted_part13.txt")
# )

# Step 3: Decompress the downloaded files (extract only .nxml to avoid images)
decompress_pubmed_files(extract_nxml_only=True)

# Step 4: Export matching captions to CSV
keywords = [
    "pathology",
    "whole slide image",
    "H&E",
    "x-ray",
    "MRI",
    "endoscopy",
    "gastrology",
    "ultrasound",
    "histopathology",
    "Adenocarcinoma",
    "Anaplastic",
    "Acute Promyelocytic Leukemia",
    "Anaplastic Thyroid Cancer",
    "Breast Cancer",
    "Basal Cell Carcinoma",
    "Bone Marrow",
    "BRCA",
    "Biopsy",
    "carcinoma",
    "Carotid Body Tumor",
    "Carcinoembryonic Antigen",
    "Chronic Granulocytic Leukemia",
    "Chromosome",
    "Cervical Intraepithelial Neoplasia",
    "Carcinoma In Situ",
    "Choroid Plexus Carcinoma",
    "Colorectal Carninoma",
    "Circulating Tumor Cell",
    "Epstein-Barr Virus",
    "EBV",
    "Epidermal Growth",
    "Extraskeletal Myxoid Chondrosarcoma",
    "Formalin Fixed Paraffin Embedded",
    "FFPE",
    "Gastrointestinal Stromal Tumors",
    "GIST",
    "Hepatocellular carcinoma",
    "Human Epidermal Growth Factor",
    "Hematoxylin and Eosin",
    "Hereditary Nonpolyposis Colon Cancer",
    "Head and Neck Squamous Cell Carcinoma",
    "Immunohistochemistry",
    "Lentigo Maligna Melanoma",
    "Malignant",
    "Metastasis",
    "Malignant Melanoma",
    "Molecular Diagnostics",
    "Nevoid Basal Cell Carcinoma Syndrome",
    "Nodular Melanoma",
    "Non Melanoma Skin Cancer",
    "Non-Small Cell Lung Cancer",
    "Renal Cell Carcinoma",
    "Sarcoma",
    "Squamous Cell Carcinoma",
    "Small Cell Lung Cancer",
    "Transitional Cell Carcinoma",
    "ALARA",
    "ARRT",
    "ASRT",
    "mammography",
    "radiography",
    "angiography",
    "angioplasty",
    "arthrogram",
    "barium",
    "chemoembolization",
    "fluroscopy",
    "hysterosalpingography",
    "hysterosonography",
    "myelogram",
    "pancreatography",
    "pyelogram",
    "radiopaque",
    "urography",
    "vasography",
    "c-arm",
    "dosimetrists",
    "esophagram",
    "fluoroscopy",
    "gantry",
    "hypoattenuating",
    "irradiation",
    "intravenous pyelography",
    "lymphangiography",
    "low-dose computed tomography",
    "magnetic resonance angiography",
    "myelography",
    "neuroradiology",
    "positron emission tomography",
    "percutaneous transhepatic cholangiography",
    "radiation",
    "scintigraphy",
    "stereotactic biopsy",
    "venogram",
    "volumetric modulated arc therapy",
    "artifact",
    "conformal radiation therapy",
    "cyclotron",
    "double-contrast barium enema",
    "endoscopic retrograde cholangiopancreatography",
    "fluoroscope",
    "image recording plate",
    "magnetic resonance imaging",
    "monoclonal antibody therapy",
    "MR spectroscopy",
    "angiogram",
    "Abdomen",
    "Achalasia",
    "Aerophagia",
    "Antispasmodics",
    "Bile",
    "Biliary tract",
    "Borborygmi",
    "Brain-gut axis",
    "Capsule Endoscopy",
    "Celiac disease",
    "Colectomy",
    "Colitis",
    "Colonoscopy",
    "Colon",
    "Colostomy",
    "Constipation",
    "Crohn's disease",
    "Cytokines",
    "Diarrhea",
    "Duodenum",
    "Dysphagia",
    "Diverticula",
    "Endoscope",
    "Endoscopy",
    "Enteritis",
    "Enterocolitis",
    "Enteroscopy",
    "Enteric nervous system",
    "Eosinophilic gastroenteritis",
    "Epithelium",
    "Esophagus",
    "Esophagitis",
    "Fistula",
    "Gastric",
    "Gastric Juices",
    "Gastritis",
    "Gastroenteritis",
    "Gastroparesis",
    "Gastroscopy",
    "Ileum",
    "Ileostomy",
    "Ingestion",
    "Laparoscopy",
    "Lymphocyte",
    "Peptic ulcer",
    "Polyp",
    "Prokinetic",
    "Protease",
    "Rectum",
    "Reuptake",
    "Villi",
]

export_keyword_captions_to_csv(
    keywords=keywords,
    output_csv_path=Path("_results/data/pubmed_caption_keywords.csv"),
)
